FIELD_REGION = 'region'
FIELD_MUNICIPALITY = 'municipality'
FIELD_SECTOR = 'sector'
FIELD_PERSON_NAME = 'name'
FIELD_PERSON_EMAIL = 'email'
FIELD_PERSON_PHONE = 'phone'
FIELD_CONTACT_METHOD_0 = 'contact-method-0'
FIELD_CONTACT_METHOD_1 = 'contact-method-1'
FIELD_CONTACT_METHOD_2 = 'contact-method-2'
FIELD_CONTACT_METHOD_3 = 'contact-method-3'
FIELD_CONTACT_METHOD_4 = 'contact-method-4'
FIELD_CONTACT_ID_0 = 'contact-id-0'
FIELD_CONTACT_ID_1 = 'contact-id-1'
FIELD_CONTACT_ID_2 = 'contact-id-2'
FIELD_CONTACT_ID_3 = 'contact-id-3'
FIELD_CONTACT_ID_4 = 'contact-id-4'
FIELD_PET_TYPE = 'type'
FIELD_PET_QUANTITY = 'quantity'
FIELD_PET_AGE = 'age-quantity'
FIELD_PET_AGE_UNITS = 'age-unit'
FIELD_DELIVERY_TIME = 'delivery-time'
FIELD_DESCRIPTION = 'description'
FIELD_PHOTO_0 = 'photo-0'
FIELD_PHOTO_1 = 'photo-1'
FIELD_PHOTO_2 = 'photo-2'
FIELD_PHOTO_3 = 'photo-3'
FIELD_PHOTO_4 = 'photo-4'

FIELD_CONTACT_INPUTS = [
    (FIELD_CONTACT_METHOD_0, FIELD_CONTACT_ID_0),
    (FIELD_CONTACT_METHOD_1, FIELD_CONTACT_ID_1),
    (FIELD_CONTACT_METHOD_2, FIELD_CONTACT_ID_2),
    (FIELD_CONTACT_METHOD_3, FIELD_CONTACT_ID_3),
    (FIELD_CONTACT_METHOD_4, FIELD_CONTACT_ID_4)
]

FIELDS_PHOTO = [
    FIELD_PHOTO_0,
    FIELD_PHOTO_1,
    FIELD_PHOTO_2,
    FIELD_PHOTO_3,
    FIELD_PHOTO_4
]
